apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: infrastructure
  lifecycle: experimental
  owner: ${{ values.owner | dump }}