openapi: 3.0.0
info:
  title: ${{ values.name }} API
  description: ${{ values.description }}
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  timestamp:
                    type: string
                    example: "2023-11-15T10:30:00.000Z"
                  uptime:
                    type: number
                    example: 123.456